export const VideosActionTypes = {
  ADD_VIDEO_TO_LIST: 'ADD_VIDEO_TO_LIST',
  REMOVE_VIDEO_FROM_LIST: 'REMOVE_VIDEO_FROM_LIST',
  REMOVE_FIRST_VIDEO_FROM_LIST: 'REMOVE_FIRST_VIDEO_FROM_LIST',
  REPLACE_VIDEOS_LIST: 'REPLACE_VIDEOS_LIST'
};